<a href="https://colab.research.google.com/github/samrudhimadane6-creator/Customer-Segmentation/blob/main/hands9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

V = np.zeros((5,5))

alpha = 0.1
gamma = 0.9

for episode in range(1000):

    state = [0,0]

    done = False

    while not done:

        action = np.random.randint(4)

        next_state = state.copy()

        if action == 0:
            next_state[0] = max(0, next_state[0]-1)

        elif action == 1:
            next_state[0] = min(4, next_state[0]+1)

        elif action == 2:
            next_state[1] = max(0, next_state[1]-1)

        else:
            next_state[1] = min(4, next_state[1]+1)

        reward = -1

        if next_state == [4,4]:
            reward = 10
            done = True

        V[state[0], state[1]] += alpha * (
            reward + gamma * V[next_state[0], next_state[1]]
            - V[state[0], state[1]]
        )

        state = next_state

print(V)

[[-9.50060682 -9.30470093 -9.14019174 -8.81710905 -8.53860187]
 [-9.36596522 -9.20650258 -8.84227054 -8.31637552 -7.75993091]
 [-9.14830413 -8.8325601  -7.94268898 -6.54523269 -4.58433352]
 [-8.71270381 -7.98937052 -6.7291777  -3.03598691  1.99465202]
 [-8.36003591 -7.6120992  -5.90357309  2.71398871  0.        ]]
